import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TurtleCode Data | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://data.turtlecode84.vercel.app">TurtleCode Data!</a>
        </h1>

        <p className={styles.description}>
          The API for all of my important databases, powered by{' '}
          <code className={styles.code}>Express.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://github.com/TurtleCode84" className={styles.card}>
            <h2>Find me on GitHub &rarr;</h2>
            <p>View my GitHub profile, public projects, and more.</p>
          </a>

          <a href="https://nextjs.org" className={styles.card}>
            <h2>Learn about Next.js &rarr;</h2>
            <p>Check out everything about Next.js on its website!</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>Use the API &rarr;</h2>
            <p>Discover the many uses & functions of this extensive API.</p>
          </a>

          <a
            href="https://data.turtlecode84.vercel.app/api"
            className={styles.card}
          >
            <h2>Example endpoint &rarr;</h2>
            <p>
              Click here to see an example of a JSON response from the API.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
           and Express.js
        </a>
      </footer>
    </div>
  )
}
